### PR TITLE
Remove docker-registry from installed packages

### PR DESCRIPTION
**Pull request by praveenkumar**
#274  Better to remove deprecated version of docker-registry and then we will see what way we should handle this issue.

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
We should wait few more days before merging this patch

**Comment by bexelbie** [comment]
@LalatenduMohanty why the delay?  We should put the reason in the PR so others can see.

@praveenkumar do you have a scratch build?

**Comment by LalatenduMohanty** [comment]
@bexelbie I thought it is understood because there is a corresponding mail in container-tools and we should give people time to see, read the mail and respond if necessary.

**Comment by LalatenduMohanty** [comment]
Looks like there is no objection with respect to removing the docker-registry from kickstart file [1]

[1] https://www.redhat.com/archives/container-tools/2016-March/msg00170.html

**Pull request merged**
