### PR TITLE
Revert landrush plugin for rhel vagrantfile

### PR DESCRIPTION
**Pull request by praveenkumar**
This patch will remove landrush plugin settings for CDK vagrantfile.

### CODE REVIEW

**Comment by praveenkumar** [comment]
Tested on Virtualbox provider, working as expected.

**Comment by LalatenduMohanty** [comment]
LGTM

**Comment by brgnepal** [comment]
ya LGTM too. Able to get xip.io in `env openshift` command through vagrant service-manager.

```
$ vagrant service-manager env openshift
# You can access the OpenShift console on: https://172.28.128.3:8443/console
# To use OpenShift CLI, run: oc login https://172.28.128.3:8443
export OPENSHIFT_URL=https://172.28.128.3:8443
export OPENSHIFT_WEB_CONSOLE=https://172.28.128.3:8443/console
export DOCKER_REGISTRY=hub.openshift.rhel-cdk.172.28.128.3.xip.io

# run following command to configure your shell:
# eval "$(vagrant service-manager env openshift)"
```

**Comment by naina-verma** [comment]
LGTM!

**Pull request merged**
