### PR TITLE
Unify Vagrantfile for different provider

### PR DESCRIPTION
**Pull request by praveenkumar**
This patch will unify Vagrantfile for different provider.

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
@praveenkumar We need to use dhcp for `config.vm.network "private_network", ip: "#{PUBLIC_ADDRESS}"`
@naina-verma can you please give it a shot on Hyper-V setup.

**Comment by praveenkumar** [comment]
> We need to use dhcp for config.vm.network 

@LalatenduMohanty  We don't really require because VSM have hook to create accessible network for providers. So I removed 
`config.vm.network "private_network", ip: "#{PUBLIC_ADDRESS}"`

**Comment by LalatenduMohanty** [comment]
> @LalatenduMohanty We don't really require because VSM have hook to create accessible network for providers.

Agree. AFAIR it creates dhcp based private network only for Virtualbox provider.

**Comment by LalatenduMohanty** [comment]
@praveenkumar can you please add this commit to 2.3.0 change log as we need to release this part of v2.3.0.

**Comment by LalatenduMohanty** [comment]
LGTM, provided @naina-verma's testing on HyperV works.

**Comment by LalatenduMohanty** [comment]
LGTM provided it works for @naina-verma in HyperV

**Comment by naina-verma** [comment]
@praveenkumar @LalatenduMohanty ,

This Vagrantfile works fine with 1.7.4 vagrant (trouble with 1.8.1 vagrant version). ACK!

**Comment by praveenkumar** [comment]
Testing done, Merging now.

**Pull request merged**
