### PR TITLE
Changing the default hostname to centos7

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
I need to test the patch

**Comment by langdon** [comment]
You don't want to just do this in the Vagrantfile? LIke does having a hostname in the kickstart matter?

**Comment by LalatenduMohanty** [comment]
@whitel I thought if we can change the hostname in the ks file then people using atlas.hasicorp also will also get benefited. Thoughts?  /.CC @kbsingh

**Comment by langdon** [comment]
I don't think it matters much either way, just pointing out you can do it in the vagrantfile.

**Comment by bexelbie** [comment]
The Centos box on atlas doesn't reset the hostname.  So I am not sure this is required.  Additionally, if we are going to set a hostname I would encourage <OS>-ADB so it is clear it is not a base box.  In this case CentOS7-ADB

**Comment by bexelbie** [comment]
Per conversation with @LalatenduMohanty and Navid on 13 October - patch will be rebased and updated with "CentOS7-ADB" and merged.

**Comment by bexelbie** [comment]
LGTM

**Pull request merged**
