### PR TITLE
marathon: embed ansible playbook in Vagrantfile

### PR DESCRIPTION
**Pull request by dustymabe**
This will enable users to copy a single file rather than having to
make sure they have the entire directory structure correct.

### CODE REVIEW

**Comment by dustymabe** [comment]
Don't merge this patch until #475 has been reviewed/merged

**Comment by LalatenduMohanty** [comment]
LGTM

**Comment by dustymabe** [comment]
ok - just rebased on top of master and updated the PR

**Comment by dustymabe** [comment]
Actually. hold off on merging. need to make one more change

**Comment by dustymabe** [comment]
Ok ready for review again :)

**Comment by LalatenduMohanty** [comment]
@dustymabe I am assuming you have tested the PR. Let me know if you want me to test it.

**Comment by LalatenduMohanty** [comment]
LGTM

**Comment by dustymabe** [comment]
@LalatenduMohanty I have been testing it, but wouldn't mind having another user try it out. Maybe @dharmit ?

**Comment by dharmit** [comment]
@dustymabe works for me. Just that I need to add `-o nonempty` for vagrant-sshfs. But I think that's not unexpected.

**Comment by dustymabe** [comment]
@dharmit I didn't change any of the vagrant-sshfs stuff so would be interesting to know why you need that.

**Comment by dharmit** [comment]
@dustymabe I just tried it again (twice) after reading your comment and it worked.

**Comment by LalatenduMohanty** [comment]
Looks like we are good here. So merging the PR.

**Pull request merged**
