### PR TITLE
Fix #554 Updated OSE to Openshift container platform

### LINKED ISSUE #554: Updated Openshift Enterprise phrase to Openshift Container Platform
Since, the Openshift have updated phrase "Openshift Enterprise" to "Openshift Container Platform" in their website, we should also update in our repo. I found only once instance where it is being used. i.e in 
[Openshift Enterprise Vagrantfile](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/rhel/rhel-ose/README.rst)

### PR DESCRIPTION
**Pull request by brgnepal**
Fix #554

### CODE REVIEW

**Comment by brgnepal** [comment]
I would recommend we first merge [Ascii doc migration PR](https://github.com/projectatomic/adb-atomic-developer-bundle/pull/552) to avoid any conflicts.

**Comment by LalatenduMohanty** [comment]
LGTM.

**Comment by LalatenduMohanty** [comment]
Thanks @budhrg

**Comment by LalatenduMohanty** [comment]
@thatdocslady @Preeticp @budhrg I got confused and merged this. What should we do now?

**Comment by brgnepal** [comment]
@LalatenduMohanty Will collaborate with @thatdocslady to solve her conflicts are she try to rebase upstream master :smile:

**Pull request merged**
