### PR TITLE
Recommended storage for docker and increasing the size of disk to 20GB

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
Scratch Build with this PR : https://cbs.centos.org/koji/taskinfo?taskID=16851 
CC @rtnpro

**Comment by langdon** [comment]
For some reason, I feel like the expected "standard" is 40g. Anyone confirm or deny? @imcleod @kbsingh

**Comment by LalatenduMohanty** [comment]
@whitel I can bump it to 40GB. It does not make any difference to the image size as this is thin provisioned.  Should I?

**Comment by LalatenduMohanty** [comment]
The scratch build works fine. Ran https://hub.docker.com/r/projectatomic/helloapache/ successfully. Not able to reproduce #44 i.e. docker pull hangs. 
@whitel  I am inclined to merge this as the patch works fine.

**Comment by LalatenduMohanty** [comment]
I have also updated the "dev-testing" images in https://atlas.hashicorp.com/atomicapp/boxes/dev-testing

**Comment by langdon** [comment]
I am not seeing the 40g change and am not worried about it either way. Otherwise, LGTM.

**Comment by LalatenduMohanty** [comment]
@whitel I have increased the disk size to 40GB now.

**Pull request merged**
