### PR TITLE
Temporary workaround for issue #154

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
I have done a scratch build with this patch : https://cbs.centos.org/koji/taskinfo?taskID=61142
Lets merge this after the scratch build is tested ok.
@praveenkumar  can you check if OpenShift is working fine with this

**Comment by LalatenduMohanty** [comment]
I have tested docker run with the build, it works fine

**Comment by bexelbie** [comment]
Works with eclipse test on mac

**Comment by praveenkumar** [comment]
Works for OpenShift origin also.

**Comment by bexelbie** [comment]
LGTM based on feedback

**Pull request merged**
