### PR TITLE
[WIP] Steps to setup the development environment for packaging using atomicapp

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
Do we need something like this as doc?

**Comment by langdon** [comment]
So, yes, but it seems a little out of left field. I think we need a more intro doc too. Something like "we recommend packaging container applications up using nulecule. See the spec [here](example.com)." and then go in to the how to. Maybe we can ask docs to take a look at the content here and think about it in general. @bexelbie are you still the right person to ask?

**Comment by bexelbie** [comment]
I am now.  I believe Atomic App is being rewritten with an API that may change the way the user uses the box.  I am starting a mailing list thread, but would appreciate your input in filling out how the user uses the ADB.  Please see: http://etherpad.osuosl.org/ADB-Story

**Comment by LalatenduMohanty** [comment]
Closing this PR as I dont think it is necessary

**Pull request closed without merging**
