### PR TITLE
Changes for release 1.8.0

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by bexelbie** [comment]
Should " +- Update with new meeting time, effective 2016-03-21 @bexelbie " be part of the Changelog?  I believe mentioning it in the release announcement is good, but I always thought our changelog was for code related changes.

**Comment by LalatenduMohanty** [comment]
@bexelbie  I am not sure. Does that mean we should not keep documentation changes part of changelog?

**Comment by bexelbie** [comment]
@LalatenduMohanty I do not consider the change of time of an IRC meeting to be a documentation change.  The meeting time does not help you use the software.  Not knowing hte meeting time doesn't hurt you when using the software.  The meeting time is a community function, not a documentation or code change.

As an example, I am sure the Linux kernel devs have at least one regular meeting.  I suspect I won't find notes about changes in their changelog.

**Comment by LalatenduMohanty** [comment]
@bexelbie  I think you are right. Will fix the changelog

**Comment by LalatenduMohanty** [comment]
@navidshaikh @bexelbie @praveenkumar I think it is ready to be merged.

**Comment by bexelbie** [comment]
LGTM

**Pull request merged**
