### PR TITLE
[Do Not Merge] Vagrantfile - testing for CI

### PR DESCRIPTION
**Pull request by dharmit**

### CODE REVIEW

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#build

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildshift

**Comment by dharmit** [comment]
#buildshift

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildshift

**Comment by dharmit** [comment]
#buildshift

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildall

**Comment by dharmit** [comment]
#buildtestjob

**Comment by dharmit** [comment]
#buildtestjob

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildshift

**Comment by dharmit** [comment]
#buildall

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildk8s

**Comment by dharmit** [comment]
#buildshift

**Comment by dharmit** [comment]
#buildkubernetes

**Comment by dharmit** [comment]
#buildkubernetes

**Comment by dharmit** [comment]
#buildkubernetes

**Comment by dharmit** [comment]
#buildkubernetes

**Comment by dharmit** [comment]
#buildkubernetes

**Comment by dharmit** [comment]
#buildall

**Comment by dharmit** [comment]
#buildkubernetes

**Comment by dharmit** [comment]
#buildall

**Comment by dharmit** [comment]
#buildall

**Comment by dharmit** [comment]
#buildall

**Comment by hferentschik** [comment]
Can we actually close this pull request now? Are you done with testing?

**Pull request closed without merging**
