### PR TITLE
Fix #428 Success message after vagrant up for k8s-singlenode-setup

### LINKED ISSUE #428: No success message after vagrant up for rhel-k8s-singlenode-setup
No success message after vagrant up for rhel-k8s-singlenode-setup

Steps to reproduce 
1. go to /cdk/components/rhel/misc/rhel-k8s-singlenode-setup
2. do vagrant up 
3. yes to registration or no (same behavior ) 

_Expected_ : 
it is not showing any successful configuration message for k8 single node as it give for rhel-ose

_Actual result_ : 
`default: Running provisioner: shell... default: Running: inline script`
It should give message at end `k8-single-node-setup configured successfully` as it gives for rhel-ose vm 
logs 

```
$ vagrant.exe up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'cdkv2'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: rhel-k8s-singlenode-setup_default_1465299221180_92959
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
default: Adapter 1: nat
default: Adapter 2: hostonly
==> default: Forwarding ports...
default: 22 => 2200 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
default: SSH address: 127.0.0.1:2200
default: SSH username: vagrant
default: SSH auth method: private key
default: Warning: Connection timeout. Retrying...
default: Warning: Connection timeout. Retrying...
default:
default: Vagrant insecure key detected. Vagrant will automatically replace
default: this with a newly generated keypair for better security.
default:
default: Inserting generated public key within guest...
default: Removing insecure key from the guest if it's present...
default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Registering box with vagrant-registration...
default: Would you like to register the system now (default: yes)? [y|n]n
==> default: Checking for guest additions in VM...
default: No guest additions were detected on the base box for this VM! Guest
default: additions are required for forwarded ports, shared folders, host only
default: networking, and more. If SSH fails on this machine, please install
default: the guest additions and repackage the box to continue.
default:
default: This is not an error message; everything may continue to work properly,
default: in which case you may ignore this message.
==> default: Configuring and enabling network interfaces...
==> default: Copying TLS certificates to C:/Users/naina/Downloads/TestingBuilds/cdk/components/rhel/misc/rhel-k8s-singlenode-setup/.vagrant/machines/default/virtualbox/docker
==> default: Rsyncing folder: /cygdrive/c/Users/naina/Downloads/TestingBuilds/cdk/components/rhel/misc/rhel-k8s-singlenode-setup/ => /vagrant
==> default: Running provisioner: shell...
default: Running: inline script
```

### PR DESCRIPTION
**Pull request by praveenkumar**
This patch will provide a success message when we do vagrant up for k8s-singlenode-setup.

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
LGTM. However I have not tested yet.

**Comment by praveenkumar** [comment]
@LalatenduMohanty I did required testing. I think it good to merge.

**Comment by LalatenduMohanty** [comment]
It failed my testing. We are getting success message even if sccli returns failure.

```
config.vm.provision "shell", run: "always", inline: <<-SHELL
    #sudo sccli kubernetes start
    sudo sccli kubernetes starts
    echo "kubernetes-single-node-setup configured successfully"
  SHELL
```

**Comment by LalatenduMohanty** [comment]
LGTM. Passed tests

**Comment by LalatenduMohanty** [comment]
@praveenkumar This PR also does not handle some negative cases. But lets fix it later.

**Pull request merged**
