### PR TITLE
Fixing networking issue with multiple nics in host

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Guthub issue #99

Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by navidshaikh** [comment]
This patch needs to be tested on the machine with multiple nics before we merge it and also test if it does not break on single nic machine. A koji build with this patch should help.

**Comment by bexelbie** [comment]
@lukaszachy can you test this on a machine with single and multiple NICs if @LalatenduMohanty gets you a build?

**Comment by LalatenduMohanty** [comment]
Need to figure out if this effects Virtualbox as well as libvirt providers.

**Comment by LalatenduMohanty** [comment]
Build of Vagrant box with the patch: https://cbs.centos.org/koji/taskinfo?taskID=50195

**Comment by LalatenduMohanty** [comment]
Looks like we are fine without this patch . Hence closing this

**Pull request closed without merging**
