### PR TITLE
Adding adb-utils, centos-release-adb 

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
…in testing tag

Also adding the RPM tree for signed RPM to the build script.

Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
Still waiting to see signed RPMs in http://mirror.centos.org/centos/7/atomic/x86_64/adb/

**Comment by LalatenduMohanty** [comment]
RPMs are now available now in http://mirror.centos.org/centos/7/atomic/x86_64/adb/. Doing a test build to see this works fine

**Comment by LalatenduMohanty** [comment]
@bexelbie @navidshaikh Build works fine with the patch. PR is ready for merging

https://cbs.centos.org/koji/taskinfo?taskID=70281 
https://cbs.centos.org/koji/taskinfo?taskID=70279

**Comment by bexelbie** [comment]
LGTM

**Pull request merged**
