### PR TITLE
Update README to add Mesos-Marathon and cache notes

### PR DESCRIPTION
**Pull request by bexelbie**
Fixes Issue #246

### CODE REVIEW

**Comment by bexelbie** [comment]
Do not merge yet - pending a patch from @Preeticp

**Comment by praveenkumar** [comment]
@Preeticp @bexelbie Is that pending patch already merged, if not can you specify which patch you are talking about?

**Comment by Preeticp** [comment]
The pending patch has been merged : https://github.com/projectatomic/adb-atomic-developer-bundle/pull/453, please go ahead and merge this one.

**Comment by praveenkumar** [comment]
@bexelbie Can you rebase your PR so I can merge that?

**Comment by bexelbie** [comment]
@praveenkumar this has been rebased (with no treble)

**Comment by praveenkumar** [comment]
Thanks @bexelbie

**Pull request merged**
