### PR TITLE
[Do Not Merge] OpenShift ADB CI

### PR DESCRIPTION
**Pull request by dharmit**

### CODE REVIEW

**Comment by dharmit** [comment]
#buildopenshift

**Comment by dharmit** [comment]
#buildopenshift

**Comment by dharmit** [comment]
#buildopenshift

**Comment by dharmit** [comment]
#buildopenshift

**Comment by dharmit** [comment]
#buildopenshift

**Comment by dharmit** [comment]
#buildall

**Comment by dharmit** [comment]
#buildall

**Comment by dharmit** [comment]
#buildall

**Comment by hferentschik** [comment]
Can we actually close this pull request now? Are you done with testing?

**Pull request closed without merging**
