### PR TITLE
Fix #351 Suppress logs from systemctl enable for kubernetes

### LINKED ISSUE #351: Suppress logs from systemctl enable for kubernetes
`systemctl enable <service_name>` send output of created symlink to `stderr` which comes as bold red line. We need to suppress it so that user not confused with it.

```
==> default: setup master
==> default:   enable etcd
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/etcd.service to /usr/lib/systemd/system/etcd.service.
==> default:   start etcd
==> default:   enable kube-apiserver
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/kube-apiserver.service to /usr/lib/systemd/system/kube-apiserver.service.
==> default:   start kube-apiserver
==> default:   enable kube-controller-manager
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/kube-controller-manager.service to /usr/lib/systemd/system/kube-controller-manager.service.
==> default:   start kube-controller-manager
==> default:   enable kube-scheduler
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/kube-scheduler.service to /usr/lib/systemd/system/kube-scheduler.service.
==> default:   start kube-scheduler
==> default: setup nodes
==> default:   enable kube-proxy
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/kube-proxy.service to /usr/lib/systemd/system/kube-proxy.service.
==> default:   start kube-proxy
==> default:   enable kubelet
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /usr/lib/systemd/system/kubelet.service.
==> default:   start kubelet
==> default:   restart docker
```

### PR DESCRIPTION
**Pull request by praveenkumar**
This will suppress logs from `systemctl enable` command.

### CODE REVIEW

**Comment by brgnepal** [comment]
LGTM

**Comment by praveenkumar** [comment]
#buildk8s

**Comment by LalatenduMohanty** [comment]
LGTM

**Comment by LalatenduMohanty** [comment]
@praveenkumar we missed the changelog here.

**Pull request merged**
