### PR TITLE
Adding suspend_mode = 'managedsave' in libvirt configuration

### PR DESCRIPTION
**Pull request by rimolive**
Work done for issue #447 to reflect the need to save work and free resources.

### CODE REVIEW

**Comment by praveenkumar** [comment]
#build

**Comment by praveenkumar** [comment]
#build_k8s

**Comment by LalatenduMohanty** [comment]
Currently discussed in https://github.com/projectatomic/adb-atomic-developer-bundle/issues/447

**Comment by LalatenduMohanty** [comment]
LGTM

**Pull request merged**
