### PR TITLE
Removing the files as these are not required with current ADB

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
@whitel  I have removed the RHEL directory (the equivalent files are present in CentOS directory) . Also I have removed some Vagrantfiles as these are not required in ADB anymore because docker service is built-in to the box now. 
The reason of removing RHEL is also that , from upstream point of view, it would be easier to give CentOS support and maintain it . Let me know what you think

**Comment by LalatenduMohanty** [comment]
@bexelbie @navidshaikh @strzibny comments?

**Comment by navidshaikh** [comment]
LGTM

**Comment by langdon** [comment]
@LalatenduMohanty  Where do you plan to provide the upstream version of the rhel vagrantfiles?

**Comment by langdon** [comment]
@LalatenduMohanty also, is the plan to ignore the vagrant-docker provider option?

**Comment by LalatenduMohanty** [comment]
@whitel I dont have any plan. Mostly because RHEL vagrant boxes are not availability in public.

With respect to vagrant-docker provider, we have relevant files in CentOS directory

**Comment by LalatenduMohanty** [comment]
@whitel I have updated the patch . It is not much different than the previous one except I am not deleting the rhel directory. I have gone through the files and we are not deleting the docker provider stuff

**Comment by langdon** [comment]
@LalatenduMohanty looks good combined with https://github.com/projectatomic/adb-atomic-developer-bundle/issues/133

**Comment by LalatenduMohanty** [comment]
@whitel thanks. Merging this.

**Pull request merged**
