### PR TITLE
Fix #318 Re-examine kube-apiserver service file to be part of kickstart

### LINKED ISSUE #318: Re-examine kube-apiserver service file to be part of kickstart
Currently we have https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/build_tools/kickstarts/centos-7-adb-vagrant.ks#L73-L100 as part of kickstart file and with current available version of kube rpm we really don't require it any more.

```
#  rpm -qa | grep kube
kubernetes-master-1.2.0-0.6.alpha1.git8632732.el7.x86_64
kubernetes-client-1.2.0-0.6.alpha1.git8632732.el7.x86_64
kubernetes-node-1.2.0-0.6.alpha1.git8632732.el7.x86_64
kubernetes-1.2.0-0.6.alpha1.git8632732.el7.x86_64


# rpm -lq kubernetes-master | grep service
/usr/lib/systemd/system/kube-apiserver.service
/usr/lib/systemd/system/kube-controller-manager.service
/usr/lib/systemd/system/kube-scheduler.service


Service file which is part of stock rpm now

$ cat /usr/lib/systemd/system/kube-apiserver.service
[Unit]
Description=Kubernetes API Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=network.target
After=etcd.service

[Service]
EnvironmentFile=-/etc/kubernetes/config
EnvironmentFile=-/etc/kubernetes/apiserver
User=kube
ExecStart=/usr/bin/kube-apiserver \
        $KUBE_LOGTOSTDERR \
        $KUBE_LOG_LEVEL \
        $KUBE_ETCD_SERVERS \
        $KUBE_API_ADDRESS \
        $KUBE_API_PORT \
        $KUBELET_PORT \
        $KUBE_ALLOW_PRIV \
        $KUBE_SERVICE_ADDRESSES \
        $KUBE_ADMISSION_CONTROL \
        $KUBE_API_ARGS
Restart=on-failure
Type=notify
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target


Service  file which we include in kickstart

$ cat /etc/systemd/system/kube-apiserver.service
[Unit]
Description=Kubernetes API Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=network.target

[Service]
EnvironmentFile=-/etc/kubernetes/config
EnvironmentFile=-/etc/kubernetes/apiserver
User=kube
ExecStart=/usr/bin/kube-apiserver \
            $KUBE_LOGTOSTDERR \
            $KUBE_LOG_LEVEL \
            $KUBE_ETCD_SERVERS \
            $KUBE_API_ADDRESS \
            $KUBE_API_PORT \
            $KUBELET_PORT \
            $KUBE_ALLOW_PRIV \
            $KUBE_SERVICE_ADDRESSES \
            $KUBE_ADMISSION_CONTROL \
            $KUBE_API_ARGS
Restart=on-failure
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```

### PR DESCRIPTION
**Pull request by praveenkumar**
I also created a scratch build for same https://cbs.centos.org/koji/taskinfo?taskID=84662 (currently task is running) will update with test for k8s VagrantFile.

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
@praveenkumar You need to update the changelog.

**Comment by praveenkumar** [comment]
@LalatenduMohanty have a look.

**Comment by LalatenduMohanty** [comment]
LGTM. Testing pending from me.

**Comment by navidshaikh** [comment]
LGTM

**Comment by LalatenduMohanty** [comment]
@praveenkumar @navidshaikh have you guys tested the scratch build with the k8s Vagrantfile?

**Comment by praveenkumar** [comment]
@LalatenduMohanty yes, I tried that build and looks kubernetes is working as expected.

```
$ kubectl get nodes
NAME        LABELS                             STATUS    AGE
127.0.0.1   kubernetes.io/hostname=127.0.0.1   Ready     33s
```

**Pull request merged**
