### PR TITLE
Added Notes: Default for ADB/CDK; Docker version mismatch; VSM steps

### LINKED ISSUE #136: vagrant adbinfo does not always contain host name
not sure when it fails, but earlier today `vagrant adbinfo` worked fine, but now I get this:

```
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:

export DOCKER_HOST=tcp://:2376
export DOCKER_CERT_PATH=/Users/max/code/cdk/.vagrant/machines/default/virtualbox/.docker
export DOCKER_TLS_VERIFY=1
export DOCKER_MACHINE_NAME=a58fb70

# run following command to configure your shell:
# eval "$(vagrant adbinfo)"
```

notice that host is blank/not-specified.

### PR DESCRIPTION
**Pull request by Preeticp**
Fixes #136, #117 from vagrant service manager repository.

### CODE REVIEW

**Comment by navidshaikh** [comment]
@Preeticp : Please update CHANGELOG file

**Comment by Preeticp** [comment]
Fixes #136 from vagrant service manager repo and #117

**Comment by praveenkumar** [comment]
@Preeticp you have to update CHANGELOG file, you might to `rebase` your branch with upstream:master so you will get latest changes.

**Comment by Preeticp** [comment]
@praveenkumar; CHANGELOG file has already been updated.

**Comment by bexelbie** [comment]
LGTM with addition of name in Changelog

**Comment by Preeticp** [comment]
Added name to the Changelog.

**Comment by navidshaikh** [comment]
LGTM

**Pull request merged**
