### PR TITLE
Fixing a couple broken links

### PR DESCRIPTION
**Pull request by shawnlower**
Also, should these urls be relative or absolute?

### CODE REVIEW

**Comment by praveenkumar** [comment]
@Preeticp , @bexelbie can you folks verify this change?

**Comment by LalatenduMohanty** [comment]
LGTM. 
@shawnlower relative url is better IMO.

**Comment by bexelbie** [comment]
+1for relative. LGTM but I'm only reading diff. @preeticp?

Welcome @shawnlower. Great to meet you!

**Comment by Preeticp** [comment]
+1 to relative links. LGTM.
Welcome and thanks @shawnlower.

**Pull request merged**
