### PR TITLE
Removing the BJN meeting

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
As we are not doing it anymore.

Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by bexelbie** [comment]
Can we re-describe the remaining meeting to make it clear that roadmap/community ideas are welcome and encouraged?  It looks like a non-planning meeting just for reporting as is.

**Comment by LalatenduMohanty** [comment]
I think we should promote the container-tools mailing list as the place to talk about ideas and roadmap and the IRC as the place to plan task.

**Comment by LalatenduMohanty** [comment]
@bexelbie IMO we don't need to explicitly mention or promote the IRC meeting and the mailing list more as compared to its current state.  So this is ready to be merged from my side.

**Comment by bexelbie** [comment]
Works for me, but please rework the nested list to better reflect that there is only one meeting.

**Comment by LalatenduMohanty** [comment]
@bexelbie sure, I have updated the PR. Let me know how it looks now.

**Comment by LalatenduMohanty** [comment]
Looks some formatting issue. Fixing it now

**Comment by bexelbie** [comment]
Can 207 and 209 be one line?  sorry to be picky ... After that merge it :)

**Comment by LalatenduMohanty** [comment]
@bexelbie done and merging it as you suggested.

**Pull request merged**
