### PR TITLE
Using systemctl to start openshift in CDK OSE Vagrantfile

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Fixes issue #342

Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by praveenkumar** [comment]
LGTM, didn't see images re-pulling issue now and `vagrant up` is working as expected for this Vagrantfile.

**Comment by LalatenduMohanty** [comment]
It passed my testing too.

**Comment by hferentschik** [comment]
Works for me as well. 1m:55s to bring up the VM.

**Comment by brgnepal** [comment]
LGTM :+1: No re-pulling of images now.

**Pull request merged**
